env:
  BUILD_DIR: "/build/cardano-wallet"
  STACK_ROOT: "/build/cardano-wallet.stack"
  CACHE_DIR: "/cache/cardano-wallet"
  LC_ALL: "en_US.UTF-8"

steps:
  - label: 'Prevent merging to wrong branch'
    if: 'build.branch == "bors/staging"'
    command: './.buildkite/check-bors.sh'
    agents:
      system: x86_64-linux
  - wait: ~
    if: 'build.branch == "bors/staging"'

  - label: 'Stack Rebuild'
    command:
      - "export TESTS_LOGDIR=$(mktemp -d)"
      - "nix-build .buildkite/default.nix -o sr"
      - "./sr/bin/rebuild --build-dir=$BUILD_DIR --cache-dir=$CACHE_DIR"
    timeout_in_minutes: 120
    artifact_paths:
      - "/build/cardano-wallet/.stack-work/logs/cardano-wallet*.log"
      - "$TESTS_LOGDIR/*.log"
    agents:
      system: x86_64-linux

  - label: 'Check Cabal Configure'
    command:
      - 'nix-shell --run "cabal v2-update"'
      - 'nix-shell --run "cabal v2-configure --enable-tests --enable-benchmarks"'
      - 'nix-shell --run "cabal v2-configure -frelease --enable-tests --enable-benchmarks"'
    agents:
      system: x86_64-linux

  - label: 'Check auto-generated Nix'
    command: './nix/regenerate.sh && nix-build ./nix -A iohkNix.checkStackProject -o check-stack-project.sh && ./check-stack-project.sh'
    agents:
      system: x86_64-linux

  - label: 'Check Stylish Haskell'
    command: 'nix-shell --run .buildkite/check-stylish.sh'
    agents:
      system: x86_64-linux

  - label: 'HLint'
    command: 'nix-shell --run "hlint lib"'
    agents:
      system: x86_64-linux

  - label: 'Validate OpenAPI Specification'
    command: 'nix-shell --run "openapi-spec-validator --schema 3.0.0 specifications/api/swagger.yaml"'
    agents:
      system: x86_64-linux

  - label: 'Docker Image'
    command:
      - "nix-build .buildkite/docker-build-push.nix --argstr dockerHubRepoName inputoutput/cardano-wallet -o docker-build-push"
      - "./docker-build-push"
    agents:
      system: x86_64-linux
    soft_fail:
      - exit_status: '*'

  - label: 'TODO list'
    command: 'nix-shell --run scripts/todo-list.sh'
    agents:
      system: x86_64-linux
